### ISSUE TITLE
何を作るか検討

### ISSUE THREAD

**Issue by oz-urabe** [oz-sysb/OpenSNS#1]
## 基本軸にしたいこと

- Rull Requet は誰からでも制限しない
    - 社外、国内、国外
- あって嬉しいもの
- 誰でも明確に理解できるように issue のワークフローや Pull Request、コーディング規約の ルールは明確にする
    - コーディング規約やルールを明確にしにくいフレームワークを使うことは避ける

**Comment by nouka** [comment]
まず手始めに、楽天商品検索APIのPHPライブラリに、最新版のAPIバージョンに対応するPRを送る。

**GitHub**
https://github.com/rakuten-ws/rws-php-sdk

**API**
https://webservice.rakuten.co.jp/api/ichibaitemsearch/

**Comment by oz-urabe** [comment]
## 話したこと

- やりたいことを一つにこだわらず、それぞれやりたいことの温度感は違うので、各々のやりたいことベースにOSSに関わる
   - PR をとある OSSになげるのもあり
   - Fork して別の OSS を作るのも有り (ライセンス確認してね)
   - OSS の起源を調べてみるのも有り
   - ゼロから作ってみるのも有り
   - 何かしらの OSS に対して PR を投げるのも有り
   - ライブラリをつくるのもあり

- 次の会までに、調べたことややったことを共有しあう
- 自分のリポジトリのスターがいっぱいつくかどうかを競争してみるのもあり
- お互いフォークして PR なげるのもあり
- 作ったものや経緯を Wantedly に投稿してみる （編集済み）

このチャットに誰かを勝手に招待してもらってもOK
